# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adrien Todeschini
description: > # this means to ignore newlines until "baseurl:"
  Adrien Todeschini's personal website.
  PhD student in Statistical Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://adrien.tspace.fr" # the base hostname & protocol for your site

# Build settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"


# Custom variables
#########################
copyright: true
ganalytics_id: UA-45407741-5
tagline: PhD student in Statistical Machine Learning
lang: en

author: 
  name: Adrien Todeschini
  email: adrien.todeschini [at] inria.fr
  adress: Inria Bordeaux – Sud-Ouest <br/> 200 avenue de la Vieille Tour <br/> 33405 Talence Cedex, France
  #phone: +33 5 2457 4160
  twitter_url:  https://twitter.com/adrtod/
  github_url:  https://github.com/adrtod/
  #bitbucket_url:  https://bitbucket.org/adrtod/
  linkedin_url:  https://fr.linkedin.com/in/adrientodeschini/en
  googleplus_url:  http://google.com/+AdrienTodeschini
  researchgate_url:  https://www.researchgate.net/profile/Adrien_Todeschini
  googlescholar_url:  https://scholar.google.fr/citations?user=ivSX6d3wzKIC&hl=en

# institutions
inria:
  name: Inria Bordeaux
  url: http://www.inria.fr/centre/bordeaux
  img: /img/inria_95px.png
imb:
  name: Institut de Mathématiques de Bordeaux
  url: http://www.math.u-bordeaux.fr/
  img: /img/imb_95px.png
univbdx:
  name: Université de Bordeaux
  url: http://www.u-bordeaux.fr/
  img: /img/univbdx_95px.gif
