# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adrien Todeschini
email: adrien.todeschini [at] inria.fr
description: > # this means to ignore newlines until "baseurl:"
  PhD student in Statistical Machine Learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adrtod.github.io/" # the base hostname & protocol for your site
github_username:  adrtod

# Build settings
#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"


# custom
author: Adrien Todeschini
copyright_year: 2013
adress: Inria Bordeaux – Sud-Ouest <br/> 200 avenue de la Vieille Tour <br/> 33405 Talence Cedex, France
phone: +33 5 2457 4160
bitbucket_username:  adrtod
linkedin_url:  https://fr.linkedin.com/in/adrientodeschini/en
googleplus_url:  http://google.com/+AdrienTodeschini
researchgate_url:  https://www.researchgate.net/profile/Adrien_Todeschini
googlescholar_url:  https://scholar.google.fr/citations?user=ivSX6d3wzKIC&hl=en
